// Created by Crowbar 0.74

$modelname "weapons/c_models/c_spy_animations.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition 24.515 -10.998 -13.739

$cdmaterials "models\weapons\c_models\spy\c_spy_viewmodel\"

$cbox 0 0 0 0 0 0

$bbox -19.114 -19.847 -47.532 41.111 68.876 20.054

$definebone "root" "" 0 46.698849 -0.827193 0 0 -179.375985 0 0 0 0 0 0
$definebone "bip_upperArm_R" "root" -8.653 -22.135235 3.978734 -17.885199 33.340349 -11.111709 0 0 0 0 0 0
$definebone "bip_lowerArm_R" "bip_upperArm_R" 0 14.313023 0.000003 0.000002 0.000009 -27.949211 0 0 0 0 0 0
$definebone "bip_hand_R" "bip_lowerArm_R" -0.000011 13.013483 -0.000005 0 0.000003 0.000002 0 0 0 0 0 0
$definebone "bip_upperArm_L" "root" 8.652996 -22.13522 3.978737 17.885199 -33.340349 168.888284 0 0 0 0 0 0
$definebone "bip_lowerArm_L" "bip_upperArm_L" 0 -14.313034 0 0.000002 0.000005 -27.949208 0 0 0 0 0 0
$definebone "bip_hand_L" "bip_lowerArm_L" -0.000004 -13.013485 -0.000004 -0.000002 0.000008 0.000002 0 0 0 0 0 0
$definebone "effect_hand_L" "bip_hand_L" -1.330879 -2.698427 0.462449 -31.35566 175.136705 -11.166123 0 0 0 0 0 0
$definebone "effect_hand_R" "bip_hand_R" 1.33091 2.698444 -0.462436 31.356128 -4.86321 11.16635 0 0 0 0 0 0
$definebone "weapon_bone" "bip_hand_R" 2.867775 3.229567 0.474423 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "weapon_bone_1" "bip_hand_R" 3.55621 4.238403 0.987502 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "weapon_bone_2" "bip_hand_R" 4.139183 5.092691 1.421975 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "weapon_bone_3" "bip_hand_R" 4.777527 6.028128 1.897721 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "weapon_bone_4" "bip_hand_R" 5.490345 7.072691 2.428969 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "weapon_bone_5" "bip_hand_R" 6.490345 7.072689 2.42897 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "weapon_bone_6" "bip_hand_R" 7.558525 6.997282 -2.354134 -15.778861 172.4936 -111.001188 0 0 0 0 0 0
$definebone "weapon_bone_7" "bip_hand_R" 7.558525 6.997282 -2.354134 15.778862 -7.5064 111.001181 0 0 0 0 0 0
$definebone "weapon_bone_L" "bip_hand_L" -2.867767 -2.740969 0.531125 33.062483 -18.439458 117.524879 0 0 0 0 0 0
$definebone "vm_weapon_bone" "bip_hand_R" 4.324081 2.744001 -0.524877 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "vm_weapon_bone_1" "bip_hand_R" 5.012512 3.752832 -0.011802 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "vm_weapon_bone_2" "bip_hand_R" 5.595486 4.607124 0.422674 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "vm_weapon_bone_3" "bip_hand_R" 6.233833 5.542564 0.898426 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "vm_weapon_bone_4" "bip_hand_R" 6.946648 6.587124 1.429667 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "vm_weapon_bone_5" "bip_hand_R" 7.537933 7.453606 1.870349 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "vm_weapon_bone_6" "bip_hand_R" 8.154472 8.357077 2.329839 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "vm_weapon_bone_7" "bip_hand_R" 8.874294 9.411907 2.866308 33.062497 -18.439469 -62.475112 0 0 0 0 0 0
$definebone "vm_weapon_bone_L" "bip_hand_L" -4.125858 -2.321501 1.394414 33.062473 -18.439455 117.524879 0 0 0 0 0 0
$definebone "vm_weapon_bone_L_1" "bip_hand_L" -4.826813 -3.348669 0.872014 33.062473 -18.439455 117.524879 0 0 0 0 0 0
$definebone "vm_weapon_bone_L_2" "bip_hand_L" -5.441669 -4.249685 0.413772 33.062473 -18.439455 117.524879 0 0 0 0 0 0
$definebone "bip_thumb_0_L" "bip_hand_L" -0.552532 -1.343527 1.604446 17.882801 -24.183004 -23.788063 0 0 0 0 0 0
$definebone "bip_thumb_0_R" "bip_hand_R" 0.552589 1.343534 -1.604463 17.882803 -24.18301 -23.788068 0 0 0 0 0 0
$definebone "bip_thumb_1_L" "bip_thumb_0_L" 0 -2.021618 -0.000004 -0.000012 0.000013 10.703373 0 0 0 0 0 0
$definebone "bip_thumb_1_R" "bip_thumb_0_R" -0.000021 2.021633 0.000027 -0.000005 0.000005 10.703363 0 0 0 0 0 0
$definebone "bip_thumb_2_L" "bip_thumb_1_L" -0.000004 -1.136217 -0.000004 -0.000007 0.000015 -12.0385 0 0 0 0 0 0
$definebone "bip_thumb_2_R" "bip_thumb_1_R" -0.000011 1.1362 -0.000019 -0.000005 0.000004 -12.038506 0 0 0 0 0 0
$definebone "bip_index_0_L" "bip_hand_L" -0.032677 -4.587727 1.352317 69.68047 142.379446 162.989474 0 0 0 0 0 0
$definebone "bip_index_0_R" "bip_hand_R" 0.032719 4.587772 -1.352291 69.68047 142.379419 162.989474 0 0 0 0 0 0
$definebone "bip_index_1_L" "bip_index_0_L" 0 -1.754536 -0.000002 0.000003 -0.000011 37.981152 0 0 0 0 0 0
$definebone "bip_index_1_R" "bip_index_0_R" -0.000006 1.75452 -0.000034 -0.000004 0.000001 37.981132 0 0 0 0 0 0
$definebone "bip_index_2_L" "bip_index_1_L" 0 -1.22702 -0.000002 -0.000004 -0.000008 5.309002 0 0 0 0 0 0
$definebone "bip_index_2_R" "bip_index_1_R" 0.000002 1.22707 0.000032 -0.000002 0.000003 5.308994 0 0 0 0 0 0
$definebone "bip_middle_0_L" "bip_hand_L" -0.367996 -4.208406 0.173244 62.549138 145.315321 168.623014 0 0 0 0 0 0
$definebone "bip_middle_0_R" "bip_hand_R" 0.368011 4.208412 -0.173239 62.549138 145.315335 168.623014 0 0 0 0 0 0
$definebone "bip_middle_1_L" "bip_middle_0_L" 0 -2.372318 -0.000004 0.000003 -0.000005 41.372198 0 0 0 0 0 0
$definebone "bip_middle_1_R" "bip_middle_0_R" -0.000006 2.372318 -0.000032 0 -0.000005 41.372187 0 0 0 0 0 0
$definebone "bip_middle_2_L" "bip_middle_1_L" 0.000004 -1.58007 -0.000001 -0.000002 -0.000003 1.962666 0 0 0 0 0 0
$definebone "bip_middle_2_R" "bip_middle_1_R" -0.000002 1.58017 0.00003 0 -0.000001 1.962672 0 0 0 0 0 0
$definebone "bip_ring_0_L" "bip_hand_L" -0.937645 -3.860697 -0.959317 57.401238 147.886136 174.420123 0 0 0 0 0 0
$definebone "bip_ring_0_R" "bip_hand_R" 0.937672 3.860714 0.959333 57.401231 147.886122 174.420137 0 0 0 0 0 0
$definebone "bip_ring_1_L" "bip_ring_0_L" 0 -1.690632 0 0 -0.000013 28.163708 0 0 0 0 0 0
$definebone "bip_ring_1_R" "bip_ring_0_R" -0.000013 1.690666 0.000021 -0.000007 -0.000006 28.163704 0 0 0 0 0 0
$definebone "bip_ring_2_L" "bip_ring_1_L" -0.000002 -1.423443 0.000002 -0.000006 -0.000015 13.419382 0 0 0 0 0 0
$definebone "bip_ring_2_R" "bip_ring_1_R" 0.000008 1.42342 0.000028 -0.000009 -0.000004 13.419379 0 0 0 0 0 0
$definebone "bip_pinky_0_L" "bip_hand_L" -1.546646 -3.404194 -1.915569 54.09615 144.066544 173.279249 0 0 0 0 0 0
$definebone "bip_pinky_0_R" "bip_hand_R" 1.546661 3.404217 1.915585 54.09616 144.06653 173.279249 0 0 0 0 0 0
$definebone "bip_pinky_1_L" "bip_pinky_0_L" 0.000004 -1.43782 0 -0.000001 -0.000008 24.348272 0 0 0 0 0 0
$definebone "bip_pinky_1_R" "bip_pinky_0_R" -0.000021 1.43787 0.000031 -0.000009 0 24.348265 0 0 0 0 0 0
$definebone "bip_pinky_2_L" "bip_pinky_1_L" -0.000002 -1.059402 0 -0.000004 -0.000005 18.453527 0 0 0 0 0 0
$definebone "bip_pinky_2_R" "bip_pinky_1_R" 0.000006 1.059372 0.000008 -0.000009 0.000003 18.45351 0 0 0 0 0 0
$definebone "Sleeve_Control" "bip_lowerArm_L" -0.000004 -13.013485 -0.000004 -0.000002 0.000008 0.000002 0 0 0 0 0 0
$definebone "Wrist_Control" "bip_lowerArm_L" 0 -10.81348 -0.000004 -0.000002 0.000008 0.000002 0 0 0 0 0 0


$sectionframes 30 134

$poseparameter "r_hand_grip" 0 12 loop 0
$poseparameter "eyelids" 0 1 loop 0
$poseparameter "valid_build_pos" 0 1 loop 0

$weightlist "weights_r_handposes" {
	 "root" 0
	 "bip_upperArm_R" 0
	 "bip_lowerArm_R" 0
	 "bip_hand_R" 0
	 "bip_upperArm_L" 0
	 "bip_lowerArm_L" 0
	 "bip_hand_L" 0
	 "effect_hand_L" 0
	 "effect_hand_R" 0
	 "weapon_bone" 1
	 "weapon_bone_1" 0
	 "weapon_bone_2" 0
	 "weapon_bone_3" 0
	 "weapon_bone_4" 0
	 "weapon_bone_5" 0
	 "weapon_bone_6" 0
	 "weapon_bone_7" 0
	 "weapon_bone_L" 0
	 "vm_weapon_bone" 1
	 "vm_weapon_bone_1" 1
	 "vm_weapon_bone_2" 1
	 "vm_weapon_bone_3" 1
	 "vm_weapon_bone_4" 1
	 "vm_weapon_bone_5" 1
	 "vm_weapon_bone_6" 1
	 "vm_weapon_bone_7" 1
	 "vm_weapon_bone_L" 0
	 "vm_weapon_bone_L_1" 0
	 "vm_weapon_bone_L_2" 0
	 "bip_thumb_0_L" 0
	 "bip_thumb_0_R" 1
	 "bip_thumb_1_L" 0
	 "bip_thumb_1_R" 1
	 "bip_thumb_2_L" 0
	 "bip_thumb_2_R" 1
	 "bip_index_0_L" 0
	 "bip_index_0_R" 1
	 "bip_index_1_L" 0
	 "bip_index_1_R" 1
	 "bip_index_2_L" 0
	 "bip_index_2_R" 1
	 "bip_middle_0_L" 0
	 "bip_middle_0_R" 1
	 "bip_middle_1_L" 0
	 "bip_middle_1_R" 1
	 "bip_middle_2_L" 0
	 "bip_middle_2_R" 1
	 "bip_ring_0_L" 0
	 "bip_ring_0_R" 1
	 "bip_ring_1_L" 0
	 "bip_ring_1_R" 1
	 "bip_ring_2_L" 0
	 "bip_ring_2_R" 1
	 "bip_pinky_0_L" 0
	 "bip_pinky_0_R" 1
	 "bip_pinky_1_L" 0
	 "bip_pinky_1_R" 1
	 "bip_pinky_2_L" 0
	 "bip_pinky_2_R" 1
	 "Sleeve_Control" 0
	 "Wrist_Control" 0
}

$weightlist "weights_layer_eyelids" {
	 "root" 0
	 "bip_upperArm_R" 0
	 "bip_lowerArm_R" 0
	 "bip_hand_R" 0
	 "bip_upperArm_L" 0
	 "bip_lowerArm_L" 0
	 "bip_hand_L" 0
	 "effect_hand_L" 0
	 "effect_hand_R" 0
	 "weapon_bone" 0
	 "weapon_bone_1" 0
	 "weapon_bone_2" 0
	 "weapon_bone_3" 0
	 "weapon_bone_4" 0
	 "weapon_bone_5" 0
	 "weapon_bone_6" 1
	 "weapon_bone_7" 1
	 "weapon_bone_L" 0
	 "vm_weapon_bone" 0
	 "vm_weapon_bone_1" 0
	 "vm_weapon_bone_2" 0
	 "vm_weapon_bone_3" 0
	 "vm_weapon_bone_4" 0
	 "vm_weapon_bone_5" 0
	 "vm_weapon_bone_6" 0
	 "vm_weapon_bone_7" 0
	 "vm_weapon_bone_L" 0
	 "vm_weapon_bone_L_1" 0
	 "vm_weapon_bone_L_2" 0
	 "bip_thumb_0_L" 0
	 "bip_thumb_0_R" 0
	 "bip_thumb_1_L" 0
	 "bip_thumb_1_R" 0
	 "bip_thumb_2_L" 0
	 "bip_thumb_2_R" 0
	 "bip_index_0_L" 0
	 "bip_index_0_R" 0
	 "bip_index_1_L" 0
	 "bip_index_1_R" 0
	 "bip_index_2_L" 0
	 "bip_index_2_R" 0
	 "bip_middle_0_L" 0
	 "bip_middle_0_R" 0
	 "bip_middle_1_L" 0
	 "bip_middle_1_R" 0
	 "bip_middle_2_L" 0
	 "bip_middle_2_R" 0
	 "bip_ring_0_L" 0
	 "bip_ring_0_R" 0
	 "bip_ring_1_L" 0
	 "bip_ring_1_R" 0
	 "bip_ring_2_L" 0
	 "bip_ring_2_R" 0
	 "bip_pinky_0_L" 0
	 "bip_pinky_0_R" 0
	 "bip_pinky_1_L" 0
	 "bip_pinky_1_R" 0
	 "bip_pinky_2_L" 0
	 "bip_pinky_2_R" 0
	 "Sleeve_Control" 0
	 "Wrist_Control" 0
}

$weightlist "weights_layer_sapper_needle" {
	 "root" 0
	 "bip_upperArm_R" 0
	 "bip_lowerArm_R" 0
	 "bip_hand_R" 0
	 "bip_upperArm_L" 0
	 "bip_lowerArm_L" 0
	 "bip_hand_L" 0
	 "effect_hand_L" 0
	 "effect_hand_R" 0
	 "weapon_bone" 0
	 "weapon_bone_1" 0
	 "weapon_bone_2" 0
	 "weapon_bone_3" 0
	 "weapon_bone_4" 0
	 "weapon_bone_5" 1
	 "weapon_bone_6" 1
	 "weapon_bone_7" 1
	 "weapon_bone_L" 0
	 "vm_weapon_bone" 0
	 "vm_weapon_bone_1" 0
	 "vm_weapon_bone_2" 0
	 "vm_weapon_bone_3" 0
	 "vm_weapon_bone_4" 0
	 "vm_weapon_bone_5" 0
	 "vm_weapon_bone_6" 0
	 "vm_weapon_bone_7" 0
	 "vm_weapon_bone_L" 0
	 "vm_weapon_bone_L_1" 0
	 "vm_weapon_bone_L_2" 0
	 "bip_thumb_0_L" 0
	 "bip_thumb_0_R" 0
	 "bip_thumb_1_L" 0
	 "bip_thumb_1_R" 0
	 "bip_thumb_2_L" 0
	 "bip_thumb_2_R" 0
	 "bip_index_0_L" 0
	 "bip_index_0_R" 0
	 "bip_index_1_L" 0
	 "bip_index_1_R" 0
	 "bip_index_2_L" 0
	 "bip_index_2_R" 0
	 "bip_middle_0_L" 0
	 "bip_middle_0_R" 0
	 "bip_middle_1_L" 0
	 "bip_middle_1_R" 0
	 "bip_middle_2_L" 0
	 "bip_middle_2_R" 0
	 "bip_ring_0_L" 0
	 "bip_ring_0_R" 0
	 "bip_ring_1_L" 0
	 "bip_ring_1_R" 0
	 "bip_ring_2_L" 0
	 "bip_ring_2_R" 0
	 "bip_pinky_0_L" 0
	 "bip_pinky_0_R" 0
	 "bip_pinky_1_L" 0
	 "bip_pinky_1_R" 0
	 "bip_pinky_2_L" 0
	 "bip_pinky_2_R" 0
	 "Sleeve_Control" 0
	 "Wrist_Control" 0
}

$weightlist "weights_layer_sd_sapper_reels" {
	 "root" 0
	 "bip_upperArm_R" 0
	 "bip_lowerArm_R" 0
	 "bip_hand_R" 0
	 "bip_upperArm_L" 0
	 "bip_lowerArm_L" 0
	 "bip_hand_L" 0
	 "effect_hand_L" 0
	 "effect_hand_R" 0
	 "weapon_bone" 0
	 "weapon_bone_1" 0
	 "weapon_bone_2" 0
	 "weapon_bone_3" 0
	 "weapon_bone_4" 0
	 "weapon_bone_5" 0
	 "weapon_bone_6" 0
	 "weapon_bone_7" 0
	 "weapon_bone_L" 0
	 "vm_weapon_bone" 1
	 "vm_weapon_bone_1" 1
	 "vm_weapon_bone_2" 0
	 "vm_weapon_bone_3" 0
	 "vm_weapon_bone_4" 0
	 "vm_weapon_bone_5" 0
	 "vm_weapon_bone_6" 0
	 "vm_weapon_bone_7" 0
	 "vm_weapon_bone_L" 0
	 "vm_weapon_bone_L_1" 0
	 "vm_weapon_bone_L_2" 0
	 "bip_thumb_0_L" 0
	 "bip_thumb_0_R" 0
	 "bip_thumb_1_L" 0
	 "bip_thumb_1_R" 0
	 "bip_thumb_2_L" 0
	 "bip_thumb_2_R" 0
	 "bip_index_0_L" 0
	 "bip_index_0_R" 0
	 "bip_index_1_L" 0
	 "bip_index_1_R" 0
	 "bip_index_2_L" 0
	 "bip_index_2_R" 0
	 "bip_middle_0_L" 0
	 "bip_middle_0_R" 0
	 "bip_middle_1_L" 0
	 "bip_middle_1_R" 0
	 "bip_middle_2_L" 0
	 "bip_middle_2_R" 0
	 "bip_ring_0_L" 0
	 "bip_ring_0_R" 0
	 "bip_ring_1_L" 0
	 "bip_ring_1_R" 0
	 "bip_ring_2_L" 0
	 "bip_ring_2_R" 0
	 "bip_pinky_0_L" 0
	 "bip_pinky_0_R" 0
	 "bip_pinky_1_L" 0
	 "bip_pinky_1_R" 0
	 "bip_pinky_2_L" 0
	 "bip_pinky_2_R" 0
	 "Sleeve_Control" 0
	 "Wrist_Control" 0
}

$animation "a_sapper_eyelid_open_corrective_animation" "c_spy_animations_anims\a_sapper_eyelid_open_corrective_animation.smd" {
	fps 30
}

$animation "a_sapper_eyelid_closed_corrective_animation" "c_spy_animations_anims\a_sapper_eyelid_closed_corrective_animation.smd" {
	fps 30
}

$animation "a_sapper_needle_left_corrective_animation" "c_spy_animations_anims\a_sapper_needle_left_corrective_animation.smd" {
	fps 30
}

$animation "a_sapper_needle_right_corrective_animation" "c_spy_animations_anims\a_sapper_needle_right_corrective_animation.smd" {
	fps 30
}

$animation "a_sd_sapper_reels_left_corrective_animation" "c_spy_animations_anims\a_sd_sapper_reels_left_corrective_animation.smd" {
	fps 30
}

$animation "a_sd_sapper_reels_right_corrective_animation" "c_spy_animations_anims\a_sd_sapper_reels_right_corrective_animation.smd" {
	fps 30
}

$animation "saxxy_pose" "c_spy_animations_anims\saxxy_pose.smd" {
	fps 30
	loop
	weightlist "weights_r_handposes"
}

$animation "bread_bagged_pose" "c_spy_animations_anims\bread_bagged_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_baguette_pose" "c_spy_animations_anims\bread_baguette_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_burnt_pose" "c_spy_animations_anims\bread_burnt_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_cinnamon_pose" "c_spy_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_cornbread_pose" "c_spy_animations_anims\bread_cornbread_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_crumpet_pose" "c_spy_animations_anims\bread_crumpet_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_pretzel_pose" "c_spy_animations_anims\bread_pretzel_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_ration_pose" "c_spy_animations_anims\bread_ration_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_robo_pose" "c_spy_animations_anims\bread_robo_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_russianblack_pose" "c_spy_animations_anims\bread_russianblack_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_shortbread_pose" "c_spy_animations_anims\bread_shortbread_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "breadmonster" "c_spy_animations_anims\breadmonster.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "a_sapper_eyelid_base" "c_spy_animations_anims\a_sapper_eyelid_base.smd" {
	fps 30
}

$animation "a_sapper_eyelid_open" "c_spy_animations_anims\a_sapper_eyelid_open.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sapper_eyelid_open_corrective_animation" 0
	weightlist "weights_layer_eyelids"
}

$animation "a_sapper_eyelid_closed" "c_spy_animations_anims\a_sapper_eyelid_closed.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sapper_eyelid_closed_corrective_animation" 0
	weightlist "weights_layer_eyelids"
}

$animation "a_sapper_needle_base" "c_spy_animations_anims\a_sapper_needle_base.smd" {
	fps 30
}

$animation "a_sapper_needle_left" "c_spy_animations_anims\a_sapper_needle_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sapper_needle_left_corrective_animation" 0
	weightlist "weights_layer_sapper_needle"
}

$animation "a_sapper_needle_right" "c_spy_animations_anims\a_sapper_needle_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sapper_needle_right_corrective_animation" 0
	weightlist "weights_layer_sapper_needle"
}

$animation "a_sd_sapper_reels_base" "c_spy_animations_anims\a_sd_sapper_reels_base.smd" {
	fps 30
}

$animation "a_sd_sapper_reels_left" "c_spy_animations_anims\a_sd_sapper_reels_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sd_sapper_reels_left_corrective_animation" 0
	weightlist "weights_layer_sd_sapper_reels"
}

$animation "a_sd_sapper_reels_right" "c_spy_animations_anims\a_sd_sapper_reels_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sd_sapper_reels_right_corrective_animation" 0
	weightlist "weights_layer_sd_sapper_reels"
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"breadmonster"
	blend "r_hand_grip" 0 12
	blendwidth 13
	fadein 0.2
	fadeout 0.2
	hidden
	realtime
}

$sequence "draw" {
	"c_spy_animations_anims\draw.smd"
	activity "ACT_SECONDARY_VM_DRAW" 1
	{ event 5004 1 "Weapon_Revolver.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "idle" {
	"c_spy_animations_anims\idle.smd"
	activity "ACT_SECONDARY_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "fire" {
	"c_spy_animations_anims\fire.smd"
	activity "ACT_SECONDARY_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "reload" {
	"c_spy_animations_anims\reload.smd"
	activity "ACT_SECONDARY_VM_RELOAD" 1
	{ event 5004 1 "Weapon_Revolver.Reload1" }
	{ event 5004 12 "Weapon_Revolver.Reload2" }
	{ event 5004 28 "Weapon_Revolver.Reload3" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "reload2" {
	"c_spy_animations_anims\reload2.smd"
	activity "ACT_SECONDARY_VM_RELOAD2" 1
	{ event 5004 1 "Weapon_Revolver.Reload1" }
	{ event 5004 12 "Weapon_Revolver.Reload2" }
	{ event 5004 28 "Weapon_Revolver.Reload3" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "eternal_draw" {
	"c_spy_animations_anims\eternal_draw.smd"
	activity "ACT_ITEM2_VM_DRAW" 1
	{ event 5004 1 "Weapon_Knife.Draw" }
	{ event 5004 10 "Weapon_Knife.Open1" }
	{ event 5004 16 "Weapon_Knife.Open5" }
	{ event 5004 22 "Weapon_Knife.Open8" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "eternal_idle" {
	"c_spy_animations_anims\eternal_idle.smd"
	activity "ACT_ITEM2_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "eternal_stab_a" {
	"c_spy_animations_anims\eternal_stab_a.smd"
	activity "ACT_ITEM2_VM_HITCENTER" 2
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "eternal_stab_b" {
	"c_spy_animations_anims\eternal_stab_b.smd"
	activity "ACT_ITEM2_VM_HITCENTER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "eternal_stab_c" {
	"c_spy_animations_anims\eternal_stab_c.smd"
	activity "ACT_ITEM2_VM_HITCENTER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "eternal_backstab" {
	"c_spy_animations_anims\eternal_backstab.smd"
	activity "ACT_ITEM2_VM_SWINGHARD" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "eternal_backstab_up" {
	"c_spy_animations_anims\eternal_backstab_up.smd"
	activity "ACT_ITEM2_BACKSTAB_VM_UP" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "eternal_backstab_down" {
	"c_spy_animations_anims\eternal_backstab_down.smd"
	activity "ACT_ITEM2_BACKSTAB_VM_DOWN" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "eternal_backstab_idle" {
	"c_spy_animations_anims\eternal_backstab_idle.smd"
	activity "ACT_ITEM2_BACKSTAB_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "eternal_stun" {
	"c_spy_animations_anims\eternal_stun.smd"
	activity "ACT_MELEE_VM_ITEM2_STUN" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "offhand_draw" {
	"c_spy_animations_anims\offhand_draw.smd"
	activity "ACT_OFFHAND_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "offhand_idle" {
	"c_spy_animations_anims\offhand_idle.smd"
	activity "ACT_OFFHAND_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "offhand_holster" {
	"c_spy_animations_anims\offhand_holster.smd"
	activity "ACT_OFFHAND_VM_HOLSTER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "melee_allclass_draw" {
	"c_spy_animations_anims\melee_allclass_draw.smd"
	activity "ACT_MELEE_ALLCLASS_VM_DRAW" 1
	{ event 5004 1 "Weapon_Machete.Draw" }
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	snap
	fps 30
}

$sequence "melee_allclass_idle" {
	"c_spy_animations_anims\melee_allclass_idle.smd"
	activity "ACT_MELEE_ALLCLASS_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	fps 30
	loop
}

$sequence "melee_allclass_swing" {
	"c_spy_animations_anims\melee_allclass_swing.smd"
	activity "ACT_MELEE_ALLCLASS_VM_HITCENTER" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	fps 30
}

$sequence "acr_draw" {
	"c_spy_animations_anims\acr_draw.smd"
	activity "ACT_ITEM1_VM_DRAW" 1
	{ event 5004 0 "Weapon_Assassin_Knife.Draw" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 35
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 85.999998 85.999998
}

$sequence "acr_idle" {
	"c_spy_animations_anims\acr_idle.smd"
	activity "ACT_ITEM1_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 35
	loop
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 86.000002 86.000002
}

$sequence "acr_stab_a" {
	"c_spy_animations_anims\acr_stab_a.smd"
	activity "ACT_ITEM1_VM_HITCENTER" 2
	fadein 0.1
	fadeout 0.2
	fps 30
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 48 48
}

$sequence "acr_stab_b" {
	"c_spy_animations_anims\acr_stab_b.smd"
	activity "ACT_ITEM1_VM_HITCENTER" 1
	fadein 0.1
	fadeout 0.2
	fps 30
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 48 48
}

$sequence "acr_stab_c" {
	"c_spy_animations_anims\acr_stab_c.smd"
	activity "ACT_ITEM1_VM_HITCENTER" 1
	fadein 0.1
	fadeout 0.2
	fps 30
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 48.000001 48.000001
}

$sequence "acr_backstab" {
	"c_spy_animations_anims\acr_backstab.smd"
	activity "ACT_ITEM1_VM_SWINGHARD" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 20
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 52.000002 52.000002
}

$sequence "acr_backstab_up" {
	"c_spy_animations_anims\acr_backstab_up.smd"
	activity "ACT_ITEM1_BACKSTAB_VM_UP" 1
	fadein 0.1
	fadeout 0.2
	fps 35
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 40.000002 40.000002
}

$sequence "acr_backstab_down" {
	"c_spy_animations_anims\acr_backstab_down.smd"
	activity "ACT_ITEM1_BACKSTAB_VM_DOWN" 1
	fadein 0.1
	fadeout 0.2
	fps 35
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 40 40
}

$sequence "acr_backstab_idle" {
	"c_spy_animations_anims\acr_backstab_idle.smd"
	activity "ACT_ITEM1_BACKSTAB_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 35
	loop
	localhierarchy "weapon_bone" "bip_lowerArm_R" range 0 0 100 100
}

$sequence "acr_stun" {
	"c_spy_animations_anims\acr_stun.smd"
	activity "ACT_MELEE_VM_ITEM1_STUN" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 35
}

$sequence "knife_draw" {
	"c_spy_animations_anims\knife_draw.smd"
	activity "ACT_MELEE_VM_DRAW" 1
	{ event 5004 1 "Weapon_Knife.Draw" }
	{ event 5004 10 "Weapon_Knife.Open1" }
	{ event 5004 16 "Weapon_Knife.Open5" }
	{ event 5004 22 "Weapon_Knife.Open8" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "knife_idle" {
	"c_spy_animations_anims\knife_idle.smd"
	activity "ACT_MELEE_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "knife_stab_a" {
	"c_spy_animations_anims\knife_stab_a.smd"
	activity "ACT_MELEE_VM_HITCENTER" 2
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "knife_stab_b" {
	"c_spy_animations_anims\knife_stab_b.smd"
	activity "ACT_MELEE_VM_HITCENTER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "knife_stab_c" {
	"c_spy_animations_anims\knife_stab_c.smd"
	activity "ACT_MELEE_VM_HITCENTER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "knife_backstab" {
	"c_spy_animations_anims\knife_backstab.smd"
	activity "ACT_MELEE_VM_SWINGHARD" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "knife_backstab_up" {
	"c_spy_animations_anims\knife_backstab_up.smd"
	activity "ACT_BACKSTAB_VM_UP" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "knife_backstab_down" {
	"c_spy_animations_anims\knife_backstab_down.smd"
	activity "ACT_BACKSTAB_VM_DOWN" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "knife_backstab_idle" {
	"c_spy_animations_anims\knife_backstab_idle.smd"
	activity "ACT_BACKSTAB_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "knife_stun" {
	"c_spy_animations_anims\knife_stun.smd"
	activity "ACT_MELEE_VM_STUN" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "c_sapper_draw" {
	"c_spy_animations_anims\c_sapper_draw.smd"
	activity "ACT_VM_DRAW" 1
	{ event 5004 1 "Weapon_Sapper.Draw" }
	{ event 5004 8 "Weapon_Sapper.DrawSwitch" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "c_sapper_drawDeployed" {
	"c_spy_animations_anims\c_sapper_drawDeployed.smd"
	activity "ACT_VM_DRAW_DEPLOYED" 1
	{ event 5004 1 "Weapon_Sapper.Draw" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "layer_eyelids" {
	"a_sapper_eyelid_open"
	"a_sapper_eyelid_closed"
	blend "eyelids" 0 1
	blendwidth 2
	delta
	fadein 0.2
	fadeout 0.2
}

$sequence "layer_sapper_needle" {
	"a_sapper_needle_left"
	"a_sapper_needle_right"
	blend "valid_build_pos" 0 1
	blendwidth 2
	delta
	fadein 0.2
	fadeout 0.2
}

$sequence "c_sapper_idle" {
	"c_spy_animations_anims\c_sapper_idle.smd"
	activity "ACT_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	addlayer "layer_sapper_needle"
	addlayer "layer_eyelids"
	fps 30
	loop
}

$sequence "throw_draw" {
	"c_spy_animations_anims\throw_draw.smd"
	activity "ACT_THROWABLE_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	snap
	fps 30
}

$sequence "throw_idle" {
	"c_spy_animations_anims\throw_idle.smd"
	activity "ACT_THROWABLE_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	fps 30
	loop
}

$sequence "throw_fire" {
	"c_spy_animations_anims\throw_fire.smd"
	activity "ACT_THROWABLE_VM_FIRE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	snap
	fps 30
}

$sequence "spell_draw" {
	"c_spy_animations_anims\spell_draw.smd"
	activity "ACT_SPELL_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "spell_fire" {
	"c_spy_animations_anims\spell_fire.smd"
	activity "ACT_SPELL_VM_FIRE" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "c_dart_gun_draw" {
	"c_spy_animations_anims\c_dart_gun_draw.smd"
	activity "ACT_PRIMARY_VM_DRAW" 1
	{ event 5004 1 "Weapon_Dart_Gun.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "c_dart_gun_idle" {
	"c_spy_animations_anims\c_dart_gun_idle.smd"
	activity "ACT_PRIMARY_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "c_dart_gun_fire" {
	"c_spy_animations_anims\c_dart_gun_fire.smd"
	activity "ACT_PRIMARY_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "c_dart_gun_reload" {
	"c_spy_animations_anims\c_dart_gun_reload.smd"
	activity "ACT_PRIMARY_VM_RELOAD" 1
	{ event 5004 1 "Weapon_Dart_Gun.Reload1" }
	{ event 5004 12 "Weapon_Dart_Gun.Reload2" }
	{ event 5004 28 "Weapon_Dart_Gun.Reload3" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "c_breadmonster_sapper_draw" {
	"c_spy_animations_anims\c_breadmonster_sapper_draw.smd"
	activity "ACT_BREADSAPPER_VM_DRAW" 1
	{ event 5004 1 "Weapon_Sapper.Draw" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "c_breadmonster_sapper_drawDeployed" {
	"c_spy_animations_anims\c_breadmonster_sapper_drawDeployed.smd"
	activity "ACT_BREADSAPPER_VM_IDLE" 1
	{ event AE_CL_PLAYSOUND 0 "Weapon_bm_sapper.snap" }
	{ event AE_CL_PLAYSOUND 28 "Weapon_bm_sapper.snap" }
	{ event AE_CL_PLAYSOUND 129 "Weapon_bm_sapper.snap" }
	{ event AE_CL_PLAYSOUND 149 "Weapon_bm_sapper.snap" }
	{ event AE_CL_PLAYSOUND 188 "Weapon_bm_sapper.snap" }
	{ event AE_CL_PLAYSOUND 60 "Weapon_bm_sapper.scream" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "secondary_inspect_start" {
	"c_spy_animations_anims\secondary_inspect_start.smd"
	activity "ACT_SECONDARY_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement1" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 40
}

$sequence "secondary_inspect_idle" {
	"c_spy_animations_anims\secondary_inspect_idle.smd"
	activity "ACT_SECONDARY_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "secondary_inspect_end" {
	"c_spy_animations_anims\secondary_inspect_end.smd"
	activity "ACT_SECONDARY_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement3" }
	{ event 5004 59 "WeaponInspect.Movement2" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "melee_inspect_start" {
	"c_spy_animations_anims\melee_inspect_start.smd"
	activity "ACT_MELEE_VM_INSPECT_START" 1
	{ event 5004 8 "Weapon_Knife.Open1" }
	{ event 5004 18 "WeaponInspect.Movement4" }
	{ event 5004 22 "Weapon_Knife.Open7" }
	{ event 5004 35 "Weapon_Knife.Open5" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 24
}

$sequence "melee_inspect_idle" {
	"c_spy_animations_anims\melee_inspect_idle.smd"
	activity "ACT_MELEE_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 24
	loop
}

$sequence "melee_inspect_end" {
	"c_spy_animations_anims\melee_inspect_end.smd"
	activity "ACT_MELEE_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement4" }
	{ event 5004 55 "WeaponInspect.Movement3" }
	{ event 5004 63 "Weapon_Knife.Open5" }
	{ event 5004 75 "Weapon_Knife.Open7" }
	fadein 0.2
	fadeout 0.2
	fps 24
}

$sequence "item2_inspect_start" {
	"c_spy_animations_anims\item2_inspect_start.smd"
	activity "ACT_ITEM2_VM_INSPECT_START" 1
	{ event 5004 11 "WeaponInspect.Movement1" }
	{ event 5004 32 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "item2_inspect_idle" {
	"c_spy_animations_anims\item2_inspect_idle.smd"
	activity "ACT_ITEM2_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "item2_inspect_end" {
	"c_spy_animations_anims\item2_inspect_end.smd"
	activity "ACT_ITEM2_VM_INSPECT_END" 1
	{ event 5004 3 "WeaponInspect.Movement2" }
	{ event 5004 61 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "item1_inspect_start" {
	"c_spy_animations_anims\item1_inspect_start.smd"
	activity "ACT_ITEM1_VM_INSPECT_START" 1
	{ event 5004 3 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "item1_inspect_idle_A" {
	"c_spy_animations_anims\item1_inspect_idle_A.smd"
	activity "ACT_ITEM1_VM_INSPECT_IDLE" 2
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "item1_inspect_idle_B" {
	"c_spy_animations_anims\item1_inspect_idle_B.smd"
	activity "ACT_ITEM1_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "item1_inspect_end" {
	"c_spy_animations_anims\item1_inspect_end.smd"
	activity "ACT_ITEM1_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement2" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "building_inspect_start" {
	"c_spy_animations_anims\building_inspect_start.smd"
	activity "ACT_BUILDING_VM_INSPECT_START" 1
	{ event 5004 4 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "building_inspect_idle" {
	"c_spy_animations_anims\building_inspect_idle.smd"
	activity "ACT_BUILDING_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "building_inspect_end" {
	"c_spy_animations_anims\building_inspect_end.smd"
	activity "ACT_BUILDING_VM_INSPECT_END" 1
	{ event 5004 55 "MeleeInspect.Movement" }
	{ event 5004 86 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "breadsapper_inspect_start" {
	"c_spy_animations_anims\breadsapper_inspect_start.smd"
	activity "ACT_BREADMONSTER_VM_INSPECT_START" 1
	{ event 5004 59 "Weapon_bm_throwable.growl" }
	{ event 5004 11 "MeleeInspect.Movement" }
	{ event 5004 32 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "breadsapper_inspect_idle" {
	"c_spy_animations_anims\breadsapper_inspect_idle.smd"
	activity "ACT_BREADMONSTER_VM_INSPECT_IDLE" 1
	{ event AE_CL_PLAYSOUND 38 "Weapon_bm_sapper.snap" }
	{ event AE_CL_PLAYSOUND 52 "Weapon_bm_sapper.snap" }
	{ event AE_CL_PLAYSOUND 91 "Weapon_bm_sapper.snap" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "breadsapper_inspect_end" {
	"c_spy_animations_anims\breadsapper_inspect_end.smd"
	activity "ACT_BREADMONSTER_VM_INSPECT_END" 1
	{ event AE_CL_PLAYSOUND 12 "Weapon_bm_sapper.snap" }
	{ event AE_CL_PLAYSOUND 29 "Weapon_bm_sapper.snap" }
	{ event 5004 2 "MeleeInspect.Movement" }
	{ event 5004 38 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "grapple_draw" {
	"c_spy_animations_anims\grapple_draw.smd"
	activity "ACT_GRAPPLE_DRAW" 1
	{ event AE_CL_PLAYSOUND 1 "WeaponGrapplingHook.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "grapple_idle" {
	"c_spy_animations_anims\grapple_idle.smd"
	activity "ACT_GRAPPLE_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "grapple_fire_start" {
	"c_spy_animations_anims\grapple_fire_start.smd"
	activity "ACT_GRAPPLE_FIRE_START" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "grapple_fire_idle" {
	"c_spy_animations_anims\grapple_fire_idle.smd"
	activity "ACT_GRAPPLE_FIRE_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "grapple_pull_start" {
	"c_spy_animations_anims\grapple_pull_start.smd"
	activity "ACT_GRAPPLE_PULL_START" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "grapple_pull_idle" {
	"c_spy_animations_anims\grapple_pull_idle.smd"
	activity "ACT_GRAPPLE_PULL_IDLE" 1
	fadein 0.1
	fadeout 0.2
	fps 30
	loop
}

$sequence "grapple_pull_end" {
	"c_spy_animations_anims\grapple_pull_end.smd"
	activity "ACT_GRAPPLE_PULL_END" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "c_sd_sapper_draw" {
	"c_spy_animations_anims\c_sd_sapper_draw.smd"
	activity "ACT_ITEM3_VM_DRAW" 1
	{ event 5004 1 "Weapon_Sapper.Draw" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "layer_sd_sapper_reels" {
	"a_sd_sapper_reels_left"
	"a_sd_sapper_reels_right"
	blend "valid_build_pos" 0 1
	blendwidth 2
	delta
	fadein 0.2
	fadeout 0.2
}

$sequence "c_sd_sapper_idle" {
	"c_spy_animations_anims\c_sd_sapper_idle.smd"
	activity "ACT_ITEM3_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	addlayer "layer_sd_sapper_reels"
	fps 30
	loop
}

$sequence "PASSTIME_ball_pickup" {
	"c_spy_animations_anims\PASSTIME_ball_pickup.smd"
	activity "ACT_BALL_VM_PICKUP" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_idle" {
	"c_spy_animations_anims\PASSTIME_ball_idle.smd"
	activity "ACT_BALL_VM_IDLE" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_catch1" {
	"c_spy_animations_anims\PASSTIME_ball_catch1.smd"
	activity "ACT_BALL_VM_CATCH" 100
	fadein 0.1
	fadeout 0.2
	fps 24
}

$sequence "PASSTIME_ball_catch2" {
	"c_spy_animations_anims\PASSTIME_ball_catch2.smd"
	activity "ACT_BALL_VM_CATCH" 1
	{ event AE_CL_PLAYSOUND 55 "BallBuster.Ball_HitWorld" }
	{ event AE_CL_PLAYSOUND 80 "Weapon_BoxingGloves.HitGlove" }
	{ event AE_CL_PLAYSOUND 90 "Weapon_BoxingGloves.HitGlove" }
	{ event AE_CL_PLAYSOUND 104 "Weapon_BoxingGloves.HitGlove" }
	{ event AE_CL_PLAYSOUND 125 "BallBuster.Ball_HitWorld" }
	{ event AE_CL_PLAYSOUND 126 "BallBuster.Ball_HitWorld" }
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_end" {
	"c_spy_animations_anims\PASSTIME_ball_throw_end.smd"
	activity "ACT_BALL_VM_THROW_END" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_start" {
	"c_spy_animations_anims\PASSTIME_ball_throw_start.smd"
	activity "ACT_BALL_VM_THROW_start" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_loop" {
	"c_spy_animations_anims\PASSTIME_ball_throw_loop.smd"
	activity "ACT_BALL_VM_THROW_LOOP" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "melee_allclass_inspect_start" {
	"c_spy_animations_anims\melee_allclass_inspect_start.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
}

$sequence "melee_allclass_inspect_idle" {
	"c_spy_animations_anims\melee_allclass_inspect_idle.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "melee_allclass_inspect_end" {
	"c_spy_animations_anims\melee_allclass_inspect_end.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_END" 1
	{ event 5004 4 "WeaponInspect.Movement3" }
	{ event 5004 70 "WeaponInspect.Movement2" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
